version: '3.8' 

services: 
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: projetobanco-db 
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ProjetoBanco@2026C#
    ports: 
      - "1433:1433" 
    volumes: 
      - sqlserver_data:/var/opt/mssql

volumes: 
  sqlserver_data:
